version: "2"
services:
  app:
    build: .
    network_mode: bridge
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/client/node_modules
      - /usr/src/app/client/build
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo/ravel
  mongo:
    image: mongo
    restart: always
    network_mode: bridge
    volumes:
      - ./mongo-data:/data/db
    command: mongod --noauth --smallfiles
